### ISSUE TITLE
RHD results

### ISSUE THREAD

**Issue by CirnoZhang** [SeanChenxy/HandMesh#35]
Hi Xingyu, I use the CMR-PG model trained on FreiHAND and eval on RHD, but only get  0.54 AUC (The average of pck20, 30, 40 is 0.268 0.466 0.634). The results on FreiHAND without problems. I think this may be caused by the difference in the joint annotations between the two datasets. Can you share the implementation details of the evaluation on RHD? 

The 4 figures below show the camera space and root-relative joints prediction, respectively. (The gray dots are the joints annotations of the image: '/RHD_published_v2/evaluation/color/00000.png'  root-relative results: pck20:0.238 pck30:0.429 pck40:0.762)
![1](https://user-images.githubusercontent.com/41942912/172349044-41eee45e-7853-4e0f-a3e3-289d4bafa733.jpg)
![compare_cam](https://user-images.githubusercontent.com/41942912/172354830-904cdca0-0ba2-4d9f-b93a-bf186bb991bc.jpg)
Left: Ground Truth; Right: Prediction

![2](https://user-images.githubusercontent.com/41942912/172349092-06519686-e687-4573-9677-101029b7d57a.jpg)
![compare_root](https://user-images.githubusercontent.com/41942912/172355342-b464c44c-fb47-470f-af24-173954decde1.jpg)

For the code for the eval part, I refer to [bihand](https://github.com/lixiny/bihand?utm_source=catalyzex.com). And I crop the image based on the hand center and the 2D joint annotation, then scaled it to 224*224 (The left hand has been flipped). 
![process](https://user-images.githubusercontent.com/41942912/172353091-92fba82b-bc31-4b83-a911-4e33a0a11566.jpg)

**Comment by SeanChenxy** [comment]
Hi, we first obtain MANO-style mesh, then get 3D pose based on MANO's joint regressor. This operation has two weaknesses: (1)  joint regressor is defined on rest pose mesh which is not very compatible to other poses; (2) as your statement, RHD's ground tuth is not compatible to MANO, i.e., 3D pose from a good mano mesh should has gap compared to RHD annotation. You can try procrustes analysis for rigid alignment. (I'm sorry that I cannot release some other code without legal review because of the change of my employment).

**Comment by CirnoZhang** [comment]
Thanks for the information!
