### ISSUE TITLE
Do you test your model on the images in the wild？

### ISSUE THREAD

**Issue by EEWenbinWu** [SeanChenxy/HandMesh#5]

**Comment by SeanChenxy** [comment]
Yes. Our model has a nice generalization. We have used it for online applications. Note that a small model size leads to better generalization.

**Comment by EEWenbinWu** [comment]
Thank you, that's great! And I also puzzle about whether your 3d mesh is the same to the MANO or not. Hope for your reply.

**Comment by SeanChenxy** [comment]
Yes, the topology is the same as MANO.

**Comment by EEWenbinWu** [comment]
好的，谢谢大佬。nice work~膜拜一下

**Comment by EEWenbinWu** [comment]
Hi, xy:
     I try your demo on my hands and get the following results, it's there any thing wrong? I use the camera_param of 20_img as my camera_param.
![image](https://user-images.githubusercontent.com/17973265/119075971-52763680-ba24-11eb-8e98-5569413da67d.png)

![image](https://user-images.githubusercontent.com/17973265/119075965-4ee2af80-ba24-11eb-8b73-1b4b7cdc612a.png)

**Comment by SeanChenxy** [comment]
Hi, camera_param is used to compute camera-space information, and the hand pose is not related to K. I have tried the first sample.  CMR-PG has the below results. Because of the lighting change, it brings errors.
![image](https://user-images.githubusercontent.com/23030658/119106558-0f7e8800-ba51-11eb-917f-f856adf960d4.png)
So, I have released CMR-G. It has smaller model size and better generalization, and we train it with FreiHAND + other data. The model has the below results. However, the silhouette predicted by this model contains the wrist, so you would want to use the 2D registration only for mesh-image alignment, i.e., set `poly=None` in `registration`.
![image](https://user-images.githubusercontent.com/23030658/119106760-350b9180-ba51-11eb-8269-a47abc73d12f.png)
Announce in advance: we will release a new version of this method working on mobile devices in 3 months.

**Comment by EEWenbinWu** [comment]
Thank you for your reply. So is there any differences between training CMR-G with others model?

**Comment by SeanChenxy** [comment]
All models have the same training setting.

**Comment by EEWenbinWu** [comment]
ok, I'll try to train a model by myself. THx for your help.

**Comment by EAST-J** [comment]
Hi, I also have the same problem when I run demo on my own images, Do you find how to change the settings or something to get the good results?

**Comment by SeanChenxy** [comment]
> Hi, I also have the same problem when I run demo on my own images, Do you find how to change the settings or something to get the good results?

Hi, thanks for your question. Please wait for days. I will update this repo and release the model for real-world test.

**Comment by EAST-J** [comment]
> > Hi, I also have the same problem when I run demo on my own images, Do you find how to change the settings or something to get the good results?
> 
> Hi, thanks for your question. Please wait for days. I will update this repo and release the model for real-world test.

Thanks for your reply, so the results for real-world example above is generated by the other trained-model instead of model which was released?

**Comment by Stephenfang51** [comment]
> Yes. Our model has a nice generalization. We have used it for online applications. Note that a small model size leads to better generalization.

@SeanChenxy  great work! Could you please tell me what inference framework for your online application ? Thanks !
